# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1f07c50a4693a06a9f9dcab6cd06311a5c31eee1119edb42b4772f4b965a7d3d44b0aaaa8d5cc9ba8478f3da5aec179dd7ba5349fda49db07535986586d2d9d1

test:
  secret_key_base: 9fbab1104b7767b6efc4dc65fa5f0f81cd099516828df5ac9b8f7cd5a5016bbdb6df36e321455ee7339df0e8996b9d872b3b5993dc7b3a63566b7a46d3158773

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
